---
title: "Monitoramento COVID-19"
subtitle: "Como usar os recursos"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

# Opções de pesquisa, filtro e reordenação

<video width="1000" height="400" autoplay loop>
  <source src="fig/tabela.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Clique e arraste para dar zoom em parcelas do gráfico.
 
 <video width="1000" height="400" autoplay loop>
  <source src="fig/zoom.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Clique e arraste os eixos para percorre-los.
 
 <video width="1000" height="400" autoplay loop>
  <source src="fig/eixos.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Passe o mouse sobre as figuras e informações serão mostradas nos rótulos.
 
<video width="1000" height="400" autoplay loop>
  <source src="fig/rotulos.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Utilize a legenda lateral para selecionar apenas algumas categorias e omitir outras. Clicar uma vez omite a categoria do gráfico. 

<video width="1000" height="400" autoplay loop>
  <source src="fig/leg_lat.webm" type="video/webm">
Your browser does not support the video tag.
</video>
 
---
 
# Utilizando clique duplo todas as são omitidas menos a de interesse.
 
<video width="1000" height="400" autoplay loop>
  <source src="fig/clique_duplo.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---
 
# Utlizando clique simples após o duplo é possível selecionar outras categorias.
 
<video width="1000" height="400" autoplay loop>
  <source src="fig/clique_simples.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---
 
# Um último clique duplo retorna para todas as categorias.

 <video width="1000" height="400" autoplay loop>
  <source src="fig/reset.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Outras opções

<video width="1000" height="400" autoplay loop>
  <source src="fig/grafico3.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---

# Exemplo de uso para as curvas

<video width="1000" height="400" autoplay loop>
  <source src="fig/curvas.webm" type="video/webm">
Your browser does not support the video tag.
</video>

---